name = "RoombaPOMDPs"
uuid = "fe2df5ea-4d44-4e5a-a895-9dbc87b19b37"
version = "0.1.0"

[deps]
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Graphics = "a2bd30eb-e257-5431-a919-1863eab51364"
Gtk = "4c0ca9eb-093a-5379-98c5-f87ac0bbbf44"
POMDPTools = "7588e00f-9cae-40de-98dc-e0c70c48cdd7"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
ParticleFilters = "c8b314e2-9260-5cf8-ae76-3be7461ca6d0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Distributions = "0.22 - 0.25"
POMDPTools = "0.9, 1"
POMDPs = "0.9, 1"
Parameters = "0.12"
ParticleFilters = "0.5"
StaticArrays = "0.12, 1"
julia = "1.6, 1"

[extras]
DiscreteValueIteration = "4b033969-44f6-5439-a48b-c11fa3648068"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "DiscreteValueIteration"]
